# Site settings
title: 草稿本
email: ty4z2008@gmail.com
description: > # 生活,技术,美食
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.microdba.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    ty4z2008
github:   ty4z2008
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
